
coment=["Excellent Sequel ,Outstanding edge of the seat thriller , poora paisa vasool 4 Star ⭐️⭐️⭐️⭐️Firstly Big big big salute to Jeetu Joseph for this masterpiece original story for Drishyam 2 . Vijay Salgaonkar returns in the 2nd installment standing strong to save his family yet again , the film is shot in Goa , there are beautiful locales , the thrill factor drives the film ,the narration & screenplay just flows organically and you just get engaged & enjoy the whole story telling ,such crisp is the screenplay . ",
        " haven’t seen Malayalam version of this movie so I won’t be comparing with it. This movie has amazing plot with some really outstanding twists and turns.  Ajay Devgn, well no one can beat him in this style of acting, his eyes and his body language are dialogues for him. New entrant in this sequel - Akshaye Khanna was outstanding and probably he only could have taken up this role",
       "I don’t think I need to go into too much detail as this is a direct continuation of the first one and it’s very very good! \nI actually didn’t think the first one was THAT great but on a strong recommendation me and hubby watched it at home, not thinking about not too much it I waited for the second instalment and I wasn’t disappointed! ",
        "I watched the movie in theaters two days ago. It was a great experience. A classic thriller movie that hits bang on the emotion of going to an extent to save the family. \nI watched Drishyam on my Television and I was blown away with the suspense till last scene and when I got to know that Part 2 is releasing I decided that day to watch it in theaters, just for the larger than life screen experience. ",
        "This movie is actually one of the masterpieces ever made in bollywood. As we know, the first installment of Drishyam franchise never disappoint us, with the same statement, one can also say that this movie is also a masterpiece. All the characters have played their role in a very magnificent way. There are no extra spiced things added such as entry of any superstar, item dance, songs (which really make some of the movies boring) and many more that you must find out watching the movie.",
        "Jeetu Joseph's original story of Drishyam 2 has been remade into an outstanding edge of the seat thriller, specially the 2nd half. Vijay Salgaonkar continues his mission to save his family in a story where screenplay just flows organically, the twists induces seeties & the climax just blows your mind. Tight screenplay that never ever deviates from building the climax, astute direction, crisp editing and most importantly, the original caste of Drishyam retained entirely is a master stroke. All actors deliver to the promise.",
        "Story - Movie start on the simple note with some details shared of the past,1st half of the movie runs on one track but Intermission comes on high note,but 2nd half Movie take a pace and story will keep you on edge and make you keen what will happen in the climax.Last 15 mins of the movie steel all the show and movie story ends on very high note.",
        "An excellent storyline with intense suspense after interval... The story gets it's true nature with the powerpact acting of Ajay Devgan and Akshay Khanna... The climax its just mind-blowing and no one can ever guess before the way story unfolds its secret... From the starting of the movie the background music helps you to sense the true suspense... The malaylam movie was diamond but is certainly a diamond with much more cuts and luster in it... Akshay khanna gives his powerful presence in almost every frame... The series is truly very very special for all the thriller lovers... Go and watch this must watch movie with no nonsense flawless story... Final Verdict: A Masterpiece indeed!",
        "Drishyam is the only movie that is getting better reviews this year. And it's because of the better story, direction, and acting.Abhishek Pathak as a director did a great job in giving Drishyam a conclusion. In the last part, it was missing and everyone wants to know what will happen if they found the body. This part clears everything up.All the actors gave their best and played their parts very briefly.",
        "",
       "",
       ]
